In [246]:
import json
from math import factorial
from itertools import combinations

# first neural network with keras make predictions
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten

import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
def read_json(filepath):
    with open(filepath) as f:
        return json.load(f)

def c(n , r):
    return factorial(n) // (factorial(n - r) * factorial(r))

In [3]:
size = 3
pgraphs = []

size_range = range(size)
combs = [combination for count in size_range for combination in combinations(size_range, count+1)]
combination_size = len(combs)

for i in range(combination_size):
    pgraphs.append(
        {
            'graph':read_json(f'graph_{i}.json'),
            'graph_data':read_json(f'graph_data_{i}.json'),
            'graph_score':read_json(f'graph_score_{i}.json'),
            'graph_accuracy':read_json(f'graph_accuracy_{i}.json')
        }
    )

In [4]:
len(pgraphs), combs

(7, [(0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)])

In [5]:
for i, ch in enumerate(['~', '7', '~', '~7', '~~', '7~', '~7~']):
    print(i, ch, pgraphs[i]['graph_accuracy'][ch], pgraphs[i]['graph'][ch])

0 ~ 0.8782051282051282 {'~': 138, 'u': 10, '6': 1, '7': 1, '8': 2, '9': 2, '1': 2}
1 7 0.25806451612903225 {'t': 2, '~': 11, '_': 2, '5': 3, '8': 2, '1': 2, '2': 2, '3': 2, '4': 2, 'c': 1, '6': 1, '7': 1}
2 ~ 0.10256410256410256 {'8': 10, '9': 7, 'c': 10, '5': 21, '6': 19, '7': 12, '1': 17, '2': 20, '3': 20, '4': 20}
3 ~7 0.6666666666666666 {'8': 2, '~': 10}
4 ~~ 0.0 {'6': 1, '7': 1, '8': 2, '9': 2, '1': 2}
5 7~ 0.125 {'5': 3, '8': 2, '1': 2, '2': 2, '3': 2, '4': 2, 'c': 1, '6': 1, '7': 1}
6 ~7~ 0.5 {'8': 2}


In [6]:
print()

[['~co', '~co', '~co', '~co', '~5~', '~6~', '~7~', '~8~', '~9~', '~co', '~co', '~co', '~co', '~co', '~co', '~7~', '~8~', '~9~'], ['~89', '~90', '~91', '~92', '~93', '~94', '~10', '~11', '~12', '~13', '~14', '~15', '~16', '~17', '~18', '~19', '~20', '~21', '~22', '~23', '~24', '~25', '~26', '~27', '~28', '~29', '~30', '~31', '~32', '~33', '~34', '~35', '~36', '~37', '~38', '~39', '~40', '~41', '~42', '~43', '~44', '~45', '~46', '~47', '~48', '~49', '~50', '~51', '~52', '~53', '~54', '~55', '~56', '~57', '~58', '~59', '~60', '~61', '~62', '~63', '~64', '~65', '~66', '~67', '~14', '~15', '~16', '~17', '~18', '~19', '~20', '~21', '~22', '~23', '~24', '~25', '~26', '~27', '~28', '~29', '~30', '~31', '~32', '~33', '~34', '~35', '~36', '~37', '~38', '~39', '~40', '~41', '~42', '~43', '~44', '~45', '~46', '~47', '~48', '~49', '~50', '~51', '~52', '~53', '~54', '~55', '~56', '~57', '~58', '~59', '~60', '~61', '~62', '~63', '~64', '~65', '~66', '~67', '~68', '~69', '~70', '~71', '~72', '~73', '~

In [17]:
data = pgraphs[0]['graph_data']['~']
X, y = [], []

rg = []
for index, li in enumerate(data):
    rg.append(len(li))
    
    for value in li:
        X.append(list(map(ord, value)))
        
X = np.array(X)
y = np.concatenate([np.zeros(rg[0]), np.ones(rg[1])])
X[y == 1]

array([[126,  56,  57],
       [126,  57,  48],
       [126,  57,  49],
       [126,  57,  50],
       [126,  57,  51],
       [126,  57,  52],
       [126,  49,  48],
       [126,  49,  49],
       [126,  49,  50],
       [126,  49,  51],
       [126,  49,  52],
       [126,  49,  53],
       [126,  49,  54],
       [126,  49,  55],
       [126,  49,  56],
       [126,  49,  57],
       [126,  50,  48],
       [126,  50,  49],
       [126,  50,  50],
       [126,  50,  51],
       [126,  50,  52],
       [126,  50,  53],
       [126,  50,  54],
       [126,  50,  55],
       [126,  50,  56],
       [126,  50,  57],
       [126,  51,  48],
       [126,  51,  49],
       [126,  51,  50],
       [126,  51,  51],
       [126,  51,  52],
       [126,  51,  53],
       [126,  51,  54],
       [126,  51,  55],
       [126,  51,  56],
       [126,  51,  57],
       [126,  52,  48],
       [126,  52,  49],
       [126,  52,  50],
       [126,  52,  51],
       [126,  52,  52],
       [126,  52

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [97]:
# define the keras model
model = Sequential()
model.add(Dense(3, input_dim=3, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# compile the keras model
model.compile(loss='mse', optimizer='adam')

In [98]:
# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=32, batch_size=16, verbose=1, validation_split=0.25)

Train on 93 samples, validate on 31 samples
Epoch 1/32
93/93 [==============================] - 0s 2ms/step - loss: 2.8150e-06 - val_loss: 2.5512e-09
Epoch 2/32
93/93 [==============================] - 0s 161us/step - loss: 1.6679e-07 - val_loss: 1.3101e-10
Epoch 3/32
93/93 [==============================] - 0s 204us/step - loss: 4.8920e-08 - val_loss: 2.2684e-11
Epoch 4/32
93/93 [==============================] - 0s 183us/step - loss: 1.7608e-08 - val_loss: 9.3814e-12
Epoch 5/32
93/93 [==============================] - 0s 226us/step - loss: 9.5063e-09 - val_loss: 7.0449e-12
Epoch 6/32
93/93 [==============================] - 0s 194us/step - loss: 6.4170e-09 - val_loss: 6.7774e-12
Epoch 7/32
93/93 [==============================] - 0s 194us/step - loss: 5.0630e-09 - val_loss: 6.9657e-12
Epoch 8/32
93/93 [==============================] - 0s 183us/step - loss: 4.3951e-09 - val_loss: 7.1269e-12
Epoch 9/32
93/93 [==============================] - 0s 183us/step - loss: 4.0460e-09 - val_los

In [144]:
len(y[y==1])

137

In [99]:
# make class predictions with the model
predictions = model.predict(X_test)

In [109]:
accuracy = ((predictions > 0.5).flatten().astype('int') == y_test).mean() * 100
print(f'accuracy = {accuracy}%')

accuracy = 100.0%


In [287]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

C:\Program Files\Python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [288]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 1.00


In [302]:
trial = '~z9'
logreg.predict(np.array([list(map(ord, trial))])), trial in data[0], trial in data[1]

(array([1.]), False, False)

In [103]:
# summarize the first 5 cases
for i in range(len(X_test)):
    print('%s => %d (expected %d)' % (X_test[i].tolist(), predictions[i] > 0.5, y_test[i]))

[126, 54, 55] => 1 (expected 1)
[126, 55, 52] => 1 (expected 1)
[126, 49, 55] => 1 (expected 1)
[126, 49, 53] => 1 (expected 1)
[126, 53, 48] => 1 (expected 1)
[126, 52, 54] => 1 (expected 1)
[126, 50, 53] => 1 (expected 1)
[126, 55, 57] => 1 (expected 1)
[126, 56, 53] => 1 (expected 1)
[126, 53, 52] => 1 (expected 1)
[126, 50, 56] => 1 (expected 1)
[126, 55, 48] => 1 (expected 1)
[126, 54, 52] => 1 (expected 1)
[126, 54, 49] => 1 (expected 1)
[126, 55, 126] => 0 (expected 0)
[126, 57, 48] => 1 (expected 1)
[126, 49, 54] => 1 (expected 1)
[126, 50, 50] => 1 (expected 1)
[126, 52, 57] => 1 (expected 1)
[126, 54, 57] => 1 (expected 1)
[126, 56, 57] => 1 (expected 1)
[126, 99, 111] => 0 (expected 0)
[126, 99, 111] => 0 (expected 0)
[126, 49, 48] => 1 (expected 1)
[126, 53, 53] => 1 (expected 1)
[126, 54, 51] => 1 (expected 1)
[126, 50, 55] => 1 (expected 1)
[126, 51, 49] => 1 (expected 1)
[126, 49, 56] => 1 (expected 1)
[126, 49, 54] => 1 (expected 1)
[126, 53, 56] => 1 (expected 1)


In [110]:
model.predict(np.array([list(map(ord, '~2~'))]))
# [list(map(ord, '123'))]

array([[0.00029663]], dtype=float32)

In [283]:
class NeuralNet:
    def __init__(self):
        # the input data
        self.x = []
        
        # the output data
        self.y = []
        
        #initialize model for training
        self.initialize_model()
        
    def initialize_model(self):
        # define the keras model
        model = Sequential()
        model.add(Dense(3, input_dim=3, activation='relu'))
        model.add(Dense(7, activation='relu'))
# #         model.add(Dense(5, activation='sigmoid'))
#         model.add(Dense(3, activation='sigmoid'))
        model.add(Dense(1))

        # compile the keras model
        model.compile(loss='binary_crossentropy', optimizer='rmsprop')
        
        # the model of the network
        self.model = model
    
    def add_data(self, context, label):
        self.x.append(list(map(ord, context)))
        self.y.append(label)
        
    def train(self):
        x, y = np.array(self.x), np.array(self.y)
        
        on, off = np.where(y==1)[0], np.where(y==0)[0]
        size = min(len(on), len(off))
        
        if len(on) < len(off):
            x = np.concatenate([x[on] for _ in range(len(off)//size)] + [x[off]])
            y = np.concatenate([y[on] for _ in range(len(off)//size)] + [y[off]])
            
        else:
            indices = np.random.randint(len(on), size=len(off))
            x = np.concatenate([x[off] for _ in range(len(on)//size)] + [x[on]])
            y = np.concatenate([y[off] for _ in range(len(on)//size)] + [y[on]])
        
        X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
        
        # fit the keras model on the dataset
        self.model.fit(X_train, y_train, epochs=16, batch_size=8, verbose=0, validation_split=0.25)
        self.model.fit(X_train, y_train, epochs=16, batch_size=8, verbose=0, validation_split=0.25)
        
        # make class predictions with the model
        predictions = self.model.predict(X_test)
        
        # calc accuracy
        accuracy = ((predictions > 0.5).flatten().astype('int') == y_test).mean()
        
        return accuracy

In [284]:
data = pgraphs[0]['graph_data']['~']

nn = NeuralNet()

for index, li in enumerate(data):
    for value in li:
        nn.add_data(value, index)

nn.train()

0.5660377358490566

In [218]:
# make class predictions with the model
predictions = nn.model.predict(X_test)

# # summarize the first 5 cases
# for i in range(len(X_test)):
#     print('%s => %d (expected %d)' % (X_test[i].tolist(), predictions[i] > 0.5, y_test[i]))